### ISSUE TITLE
[BUG] no attribute 'frame_width'

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#278]
### Description

The frame width and height attributes seems to be the wrong ones when using ManimGL.
One should inspect the ManimGL Scene class and check how to get such information.

See error message:

```
➜  manim-slides git:(main) ✗ poetry run manimgl manimgl_fail.py 
ManimGL v1.6.1
[14:10:28] INFO     Using the default configuration file, which you can modify in           config.py:265
                    `/home/jeertmans/.cache/pypoetry/virtualenvs/manim-slides-Y_qmLdW--py3.              
                    8/lib/python3.8/site-packages/manimlib/default_config.yml`                           
           INFO     If you want to create a local configuration file, you can create a file config.py:266
                    named `custom_config.yml`, or run `manimgl --config`                                 
[14:10:29] WARNING  Unsupported element type: <class 'svgelements.svgelements.Use'>    svg_mobject.py:174
           WARNING  Unsupported element type: <class 'svgelements.svgelements.Use'>    svg_mobject.py:174
           WARNING  Unsupported element type: <class 'svgelements.svgelements.Use'>    svg_mobject.py:174
           WARNING  Unsupported element type: <class 'svgelements.svgelements.Use'>    svg_mobject.py:174
           WARNING  Unsupported element type: <class 'svgelements.svgelements.Use'>    svg_mobject.py:174
           WARNING  Unsupported element type: <class 'svgelements.svgelements.Use'>    svg_mobject.py:174
           WARNING  Unsupported element type: <class 'svgelements.svgelements.Use'>    svg_mobject.py:174
/home/jeertmans/.cache/pypoetry/virtualenvs/manim-slides-Y_qmLdW--py3.8/lib/python3.8/site-packages/manimlib/utils/space_ops.py:155: RuntimeWarning: invalid value encountered in scalar divide
  cos_angle = np.dot(v1, v2) / np.float64(n1 * n2)
           WARNING  Unsupported element type: <class 'svgelements.svgelements.Use'>    svg_mobject.py:174
           WARNING  Unsupported element type: <class 'svgelements.svgelements.Use'>    svg_mobject.py:174
           WARNING  Unsupported element type: <class 'svgelements.svgelements.Use'>    svg_mobject.py:174
Traceback (most recent call last):
  File "/home/jeertmans/.cache/pypoetry/virtualenvs/manim-slides-Y_qmLdW--py3.8/bin/manimgl", line 8, in <module>
    sys.exit(main())
  File "/home/jeertmans/.cache/pypoetry/virtualenvs/manim-slides-Y_qmLdW--py3.8/lib/python3.8/site-packages/manimlib/__main__.py", line 25, in main
    scene.run()
  File "/home/jeertmans/repositories/manim-slides/manim_slides/slide.py", line 536, in run
    super().run(*args, **kwargs)
  File "/home/jeertmans/.cache/pypoetry/virtualenvs/manim-slides-Y_qmLdW--py3.8/lib/python3.8/site-packages/manimlib/scene/scene.py", line 91, in run
    self.construct()
  File "manimgl_fail.py", line 9, in construct
    self.play(self.wipe(text, Text("Wiped!")))
  File "/home/jeertmans/repositories/manim-slides/manim_slides/slide.py", line 601, in wipe
    [self.__frame_width, self.__frame_height, 0.0]
  File "/home/jeertmans/repositories/manim-slides/manim_slides/slide.py", line 76, in __frame_width
    return self.frame_width  # type: ignore
AttributeError: 'Main' object has no attribute 'frame_width'
```

From this code:

```python
from manimlib import *
from manim_slides import Slide

class Main(Slide):
    def construct(self):
        text = Text("Text")
        self.play(FadeIn(text))
        self.next_slide()
        self.play(self.wipe(text, Text("Wiped!")))
```

### Version

v5.0.0-rc1

### Platform

All

**Comment by Dv04** [comment]
Hey, I would like to work on this issue. Can I get assigned to this?

**Comment by jeertmans** [comment]
Hey, yes of course :)

**Comment by Dv04** [comment]
Hey, I think I have the code ready but can I get the destination for the manimgl_fail.py?

**Comment by jeertmans** [comment]
What do you by the destination?

if your code is ready, then rendering the example above should work :)

**Comment by Dv04** [comment]
I would like to know solution to one issue:

I am using MacOS and I encountered a particular error which, after I searched, has been encountered by other Mac users as well. Would you explain me the following issue. I tried following what they have already done but that resulted in a failure.

(.venv) apple@MacBook-Air manim % manimgl example_scenes.py OpeningManimExample

Traceback (most recent call last):
  File "/opt/homebrew/bin/manimgl", line 5, in <module>
    from manimlib.__main__ import main
ModuleNotFoundError: No module named 'manimlib.__main__'

<img width="1440" alt="Screenshot 2023-10-02 at 7 30 15 PM" src="https://github.com/jeertmans/manim-slides/assets/62090715/9bb68741-ae4e-4861-b133-3bda8acce449">

I followed all the installation manuals found in your docs for manim/manimgl/manim-slides already. so if I am missing something, please inform me of it. Thank you.

**Comment by jeertmans** [comment]
Are you using Poetry? If so, then you should prepend `poetry run` to your commands. E.g., `poetry run manimgl ...`.

You also first have to install ManimGL, with `poetry install --all-extras`.
