### ISSUE TITLE
[BUG] ImportError when running `manim-slides` on OpenSUSE

### ISSUE THREAD

**Issue by frecio231** [jeertmans/manim-slides#341]
### Description

When I try to run `manim-slides` I get the next error

```
Traceback (most recent call last):
  File "/home/fernando/miniconda3/envs/manim/bin/manim-slides", line 5, in <module>
    from manim_slides.__main__ import cli
  File "/home/fernando/miniconda3/envs/manim/lib/python3.11/site-packages/manim_slides/__main__.py", line 8, in <module>
    from .convert import convert
  File "/home/fernando/miniconda3/envs/manim/lib/python3.11/site-packages/manim_slides/convert.py", line 40, in <module>
    from .present import get_scenes_presentation_config
  File "/home/fernando/miniconda3/envs/manim/lib/python3.11/site-packages/manim_slides/present/__init__.py", line 15, in <module>
    from .player import Player
  File "/home/fernando/miniconda3/envs/manim/lib/python3.11/site-packages/manim_slides/present/player.py", line 6, in <module>
    from PySide6.QtMultimedia import QMediaPlayer
ImportError: /lib64/libgssapi_krb5.so.2: undefined symbol: k5_buf_cstring, version krb5support_0_MIT
```

It doesn't matter if is `manim-slides wizard` or some rendered scene.

### Version

according to `pip list | grep manim-slides` is version 5.0.0, not able to run `manim-slides --version`, get the same error

When running `zypper info krb5`
```
Información para paquete krb5:
------------------------------
Repositorio           : openSUSE:Tumbleweed
Nombre                : krb5
Versión               : 1.21.1-2.1
Arquitectura          : x86_64
Proveedor             : openSUSE
Tamaño de instalación : 2.2 MiB
Instalado             : Sí
Estado                : actualizado
Paquete de fuentes    : krb5-1.21.1-2.1.src
URL ascendente        : https://kerberos.org/dist/
Resumen               : MIT Kerberos5 implementation
Descripción           : 
    Kerberos V5 is a trusted-third-party network authentication system,
    which can improve network security by eliminating the insecure
    practice of clear text passwords.
```

### Platform

OpenSUSE Tumbleweed but using conda `cat /usr/lib/os-release`

```
NAME="openSUSE Tumbleweed"
# VERSION="20231208"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20231208"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20231208"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
```

`conda --version`
`conda 23.11.0`

`python --version`(on the virtual environment)
`Python 3.11.7`

**Comment by jeertmans** [comment]
Hello, that looks like an interesting error!

Unfortunately, I am not familiar with OpenSUSE, and I am worried that the error may come from incompatibility for that OS from Qt (or PySide6).

I have found some (maybe) related issues on the web:

- https://bugreports.qt.io/browse/PYSIDE-1950;
- https://forum.qt.io/topic/132419/pyside6-dependency-problem-within-virtual-python-environment/6.

Can you take a look a those and come back to me if that helped?

**Comment by jeertmans** [comment]
Closing, as I did not receive any update from the author in almost a year. Feel free to re-open this if you think it is appropriate.
