### ISSUE TITLE
[BUG] running "manim-slides" command only gives an "Aborted (core dumped)" error

### ISSUE THREAD

**Issue by AnasIbrahim1** [jeertmans/manim-slides#348]
### Description

When I try to run "manim-slides" as a command only anywhere, it gives this error message
```
Traceback (most recent call last):
  File "signature_bootstrap.py", line 77, in bootstrap
  File "signature_bootstrap.py", line 93, in find_incarnated_files
  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Fatal Python error: could not initialize part 2
Python runtime state: initialized

Current thread 0x00007f2783efd000 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1176 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 674 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1078 in _handle_fromlist
  File "/home/group03-f23/.local/lib/python3.10/site-packages/PySide6/__init__.py", line 64 in _setupQtDirectories
  File "/home/group03-f23/.local/lib/python3.10/site-packages/PySide6/__init__.py", line 124 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 992 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/home/group03-f23/.local/lib/python3.10/site-packages/manim_slides/config.py", line 17 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/home/group03-f23/.local/lib/python3.10/site-packages/manim_slides/convert.py", line 38 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/home/group03-f23/.local/lib/python3.10/site-packages/manim_slides/__main__.py", line 8 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/home/group03-f23/.local/bin/manim-slides", line 5 in <module>

Extension modules: charset_normalizer.md, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, lxml._elementpath, lxml.etree, PIL._imaging, PIL._imagingft, markupsafe._speedups, xxsubtype, apt_pkg (total: 21)
Aborted (core dumped)
```

This also seems to happen whenever I run
```
manim -pqh scene.py SquareToCircle
```
or any other scene where the file `scene.py` contains the line `from manim_slides import Slide` (while running correctly using anything without manim-slides)

This happened when I upgraded `PySide6` with `pip install --upgrade PySide6` to fix a small flickering issue in the html slides, and then I reinstalled `manim-slides`

Now, whenever I say `pip show PySide` it says `WARNING: Package(s) not found: PySide` while before it used to show the backage.

I tried uninstalling manim-slides and installing it again, and it says successfully installed but then whenever I run `manim-slides --version` another very similar `Abort (core dumped)` error appears.

Whenever I try running `pip install PySide` it gives this error
```
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Any ideas?

### Version

5.0.0

### Platform

Ubuntu 22.04.3

**Comment by jeertmans** [comment]
Hello! Thanks for reporting this issue!

First, let me point that `PySide` is not the same package `PySide6`. Second, it is very likely that installing the correct PySide6 version may not be possible on your OS version, as it is the case for others.

What does `pip show PySide6` outputs? The flickering issue is caused by a non-valid PySide6 version, this is a known issue, see #293 and https://github.com/jeertmans/manim-slides/issues/315#issuecomment-1818442857.

Can you try installing another version of PySide6? Any version between `>=6.5.0` and `<6.5.3` should all work.

Last, next version will not require a specific backend thanks to #350. So you will be able to use PyQT instead, that may work better.

**Comment by AnasIbrahim1** [comment]
This is what `pip show PySide6` outputs:
```
Name: PySide6
Version: 6.5.2
Summary: Python bindings for the Qt cross-platform application and UI framework
Home-page: https://www.pyside.org
Author: Qt for Python Team
Author-email: pyside@qt-project.org
License: LGPL
Location: /home/group03-f23/.local/lib/python3.10/site-packages
Requires: PySide6-Addons, PySide6-Essentials, shiboken6
Required-by: manim-slides
```

**Comment by jeertmans** [comment]
The version should be ok!
Then I highly recommend to install Manim-Slide in a separate environment. A nice tool for that is pipx. 

First, uninstall Manim slides and make sure that running the command outputs an error message « command not found » or equivalent.

You can then install the necessary package with: ˋpipx install manim-slides[manim]ˋ.

**Comment by AnasIbrahim1** [comment]
`pipx` will create the expected issue of not being able to compile a python file with this error `ModuleNotFoundError: No module named 'manim_slides'`

**Comment by jeertmans** [comment]
My bad! Actually you need to install version 5.1.0-rc2

This is unreleased at the moment, so it will not use this version if you do not specify it.

then, render sliders using 
manim-slides render -pqh scene.py SquareToCircle

this should hopefully work :)

**Comment by AnasIbrahim1** [comment]
This unfortunately didn't work, however, when I tried these commands:
```
pip install manim-slides
pip install pip-autoremove
pip-autoremove manim-slides
pip install manim-slides
```
Everything works now perfectly. What this did is that `pip-autoremove` removes a python package along with its dependencies. So, when I cleared all dependencies for `manim-slides` and installed it again, somehow something was fixed :)
Thanks anyways!

**Comment by jeertmans** [comment]
Happy it solved that!

The pros of using pipx are dependencies isolation, which help avoiding using manim-slides from one Python environnement, but Manim from another one.

I hope to make installation simpler in the future :)
