### ISSUE TITLE
QVideoWidget object hs no attribute videoSink

### ISSUE THREAD

**Issue by samyytids** [jeertmans/manim-slides#370]
### Please explain the issue you're experiencing (with as much detail as possible):

When I try to run any manim project using manim-slides I get the following error:

manim-slides BasicExample
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/home/samyytids/seminars/rm/seminar-3/venv/bin/manim-slides", line 8, in <module>
    sys.exit(cli())
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/manim_slides/present/__init__.py", line 305, in present
    player = Player(
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/manim_slides/present/player.py", line 229, in __init__
    self.video_sink = self.video_widget.videoSink()
AttributeError: 'QVideoWidget' object has no attribute 'videoSink'

I can't seem to find anything to fix this error, it occurs in a venv and with any project. 
I'm using ubuntu, sorry if I'm just missing something really obvious I feel like I have tried everything at this point.

Many thanks in advance!

**Comment by jeertmans** [comment]
Hello! To help you, I need to need to know the version of Manim Slides you are using, as well as the Qt bindings and their version.

You can obtain this information with `pip freeze`.

**Comment by samyytids** [comment]
Hello,

First off thanks for responding!

qt5-applications==5.15.2.2.3
qt5-tools==5.15.2.1.3
QtPy==2.4.1
manim==0.18.0
manim-slides==5.1.2

If this turns out to just be a versioning issue I am going to be so annoyed!

**Comment by jeertmans** [comment]
So the requirements you are listing do not include any Qt binding (`qt5-applications` and `qt5-tools` are not useful to Manim Slides), but you need some, see [here](https://manim-slides.eertmans.be/v5.1.2/installation.html#when-you-need-a-qt-backend).

If you didn't any Qt bindings installed, then you would have this error:

```bash
qtpy.QtBindingsNotFoundError: No Qt bindings could be found
```

Because you have another error, you have probably another Qt library installed, but that you did not list above. Because it uses `qtpy`, it should be one of the following: `PyQt5`, `PyQt6`, `PySide2`, or `PySide6`.

Can you maybe share the full output of `pip freeze`? Also, make sure that `pip` uses the same Python environment as `manim-slides`. 

A good way to do so is via Python modules:

```bash
python -m pip freeze
python -m manim_slides BasicExample
```

> [!NOTE]
> Here, `manim_slides` takes an underscore, because it uses its module name.

Last but not least, if you are on `Python < 3.12`, then I highly recommend using

```bash
pip install manim-slides[pyside6]
```

to avoid those kinds of issues.

**Comment by jeertmans** [comment]
Thanks!

Still the same error?

Also, are you sure to run from the correct Python environment?
Because I have the exact same Python dependencies as you listed above, and it works :/

**Comment by samyytids** [comment]
How strange, I'm pretty sure it's running from the same environment.

To double check in case I've missed something obvious here, here's a step by step of what I have done so far. 

open vsc
python -m venv venv
source venv/bin/activate
terminal now has (venv) blah blah blah 
pip install (insert stuff listed above)
manim file.py NameOfPresentation
python -m manim_slides NameOfPresentation

I then get this error still: 
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/manim_slides/__main__.py", line 73, in <module>
    cli()
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/manim_slides/present/__init__.py", line 305, in present
    player = Player(
  File "/home/samyytids/seminars/rm/seminar-3/venv/lib/python3.10/site-packages/manim_slides/present/player.py", line 229, in __init__
    self.video_sink = self.video_widget.videoSink()
AttributeError: 'QVideoWidget' object has no attribute 'videoSink'

**Comment by jeertmans** [comment]
Hum weird... can you try with `python -m pip install "manim-slides[pyside6]"`?

Not sure if `pip` points to the one from your venv on Windows.

**Comment by samyytids** [comment]
Apparently that fixed it!

Thank you so much!

**Comment by jeertmans** [comment]
You are welcome :)
This is probably because Windows’s virtual environments expose pip3 and not pip, so pip points to your system installation :)

Glad it solved your issue :)
