### ISSUE TITLE
"manim-slides wizard" running error

### ISSUE THREAD

**Issue by nn-heckfy** [jeertmans/manim-slides#391]
### Please explain the issue you're experiencing (with as much detail as possible):

Greetings. When I try to change the keybind using the command **"manim-slides wizard"** I get the following error: 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Heckfy\AppData\Local\Programs\Python\Python311\Scripts\manim-slides.exe\__main__.py", line 7, in <module>
  File "C:\Users\Heckfy\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Heckfy\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Heckfy\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Heckfy\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Heckfy\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
    return _init(config_path, force, merge, skip_interactive=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Heckfy\AppData\Local\Programs\Python\Python311\Lib\site-packages\manim_slides\wizard\__init__.py", line 67, in _init   
    from .wizard import Wizard
  File "C:\Users\Heckfy\AppData\Local\Programs\Python\Python311\Lib\site-packages\manim_slides\wizard\wizard.py", line 24, in <module>  
    for key in Qt.Key:
TypeError: 'sip.enumtype' object is not iterable

Any ideas on how to fix it? Thanks in advance.

**Comment by nn-heckfy** [comment]
Command **"pip install manim-slides[pyside6]"** solve the problem.

**Comment by jeertmans** [comment]
Nice, happy you found a solution!

A "clean" fresh installation is often the easiest way to fix that kind of issues. This is also why I recommend using a virtual environment just for Manim Slides :-)
