### ISSUE TITLE
[BUG] manim-slides no longer work on M1 chip

### ISSUE THREAD

**Issue by HadiSDev** [jeertmans/manim-slides#53]
### Description

manim-slides no longer work on M1 chip (or arm64) because of pyqt5. Using Rosetta terminal is not an option.

### Version

v.4.2.0

### Platform

macOS arm64

### Additional information

```
pip install manim-slides==4.2.0
Collecting manim-slides==4.2.0
  Using cached manim-slides-4.2.0.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.62.3 in /Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages (from manim-slides==4.2.0) (4.64.1)
Requirement already satisfied: numpy>=1.19.3 in /Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages (from manim-slides==4.2.0) (1.23.4)
Requirement already satisfied: click>=8.0 in /Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages (from manim-slides==4.2.0) (8.1.3)
Requirement already satisfied: opencv-python>=4.6 in /Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages (from manim-slides==4.2.0) (4.6.0.66)
Collecting pyqt5>=5.15
  Using cached PyQt5-5.15.7.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/xxxx/Library/Caches/pypoetry/virtualenvs/ai-conf-presentation-myrB_ykU-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 69, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/15/yly5qc49661d3rkdfl04fnvc0000gp/T/pip-build-env-pxb2eug4/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by jeertmans** [comment]
Hi @HadiSDev, thank you for your feedback, and I'm very sorry to see that it breaks on M1 chips.

Did you already check that discussion? https://stackoverflow.com/questions/65901162/how-can-i-run-pyqt5-on-my-mac-with-m1chip-ppc64el-architecture

I'm not on a Mac computer, but I will try to create a pipeline to test if it works on M1 chips too.

**Comment by HadiSDev** [comment]
Hi @jeertmans. I have tried to install pyqt5 locally as instructed in the link provided but pip still tries to install it its own way regardless. I think that any arm chip should have the same issue but I have not checked that to be sure.

**Comment by jeertmans** [comment]
For the moment, GitHub actions do not support M1 chips (see [#2187](https://github.com/actions/runner-images/issues/2187)). I have looked at alternatives, such as CircleCI, but they also [lack support](https://circleci.canny.io/cloud-feature-requests/p/support-new-m1-arm-based-macs) for M1 chips.

As such, I'm afraid it's hard for me to test anything related to M1 chips.
If you can, I would really appreciate if you find a solution, so that it can be documented here.

**Comment by jeertmans** [comment]
Hi @HadiSDev! Looks like PySide6 has support for M1 chips. Would you mind testing installing `pip install pyside6`?

If it works, I might try to move from PyQT5 to PySide6, since they apparently share most of their API.
